// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package epoll

import (
	"github.com/mailru/easyjson/jlexer"
	"github.com/mailru/easyjson/jwriter"
)

func (Config) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*Config) UnmarshalJSON([]byte) error        { return nil }
func (Config) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*Config) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Config *Config

func (ConfigItem) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*ConfigItem) UnmarshalJSON([]byte) error        { return nil }
func (ConfigItem) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*ConfigItem) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ConfigItem *ConfigItem
